fix ecr permissions

diff --git a/jenkins-jobs/nginx-docker-build/Jenkinsfile b/jenkins-jobs/nginx-docker-build/Jenkinsfile
--- a/jenkins-jobs/nginx-docker-build/Jenkinsfile
+++ b/jenkins-jobs/nginx-docker-build/Jenkinsfile
@@ -47,6 +47,28 @@ spec:
     }
     
     stages {
+        stage('Wait for Docker') {
+            steps {
+                container('docker') {
+                    echo 'Waiting for Docker daemon to be ready...'
+                    sh '''
+                        timeout=60
+                        while ! docker info >/dev/null 2>&1; do
+                            if [ $timeout -le 0 ]; then
+                                echo "Docker daemon failed to start within 60 seconds"
+                                exit 1
+                            fi
+                            echo "Waiting for Docker daemon... ($timeout seconds remaining)"
+                            sleep 2
+                            timeout=$((timeout - 2))
+                        done
+                        echo "Docker daemon is ready!"
+                        docker info
+                    '''
+                }
+            }
+        }
+        
         stage('Checkout') {
             steps {
                 echo 'Checking out source code...'
